config/routes.rb
Rails.application.routes.draw do


  get 'book/index'

  get 'book/new'

  get 'book/edit'

  get 'book/show'

  get 'publishers/index'

  get 'publishers/show'

  get 'publishers/new'

  get 'publishers/edit'

  get 'categories/new'

  get 'authors/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'books#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  # Add new routes for logging in/out
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :categories do
    resources :books
  end 
  resources :authors do
    resources :books
  end 
   resources :publishers do
    resources :books
  end 
  
  resources :users
  resources :books do
  resources :reviews
  end
  resources :publishers
  resources :authors
  resources :categories
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :relationships,       only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  

  validates :title, presence: true
  belongs_to :author
  accepts_nested_attributes_for :author
  belongs_to :publisher
  accepts_nested_attributes_for :publisher
  belongs_to :category
  accepts_nested_attributes_for :category
  has_many :reviews
  has_attached_file :book_img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
    has_many :passive_relationships, class_name:  "Relationship",
             foreign_key: "followed_id",
             dependent:   :destroy
    has_many :followers, through: :passive_relationships, source: :follower

    def author_attributes=(attributes)
      self.author = Author.find_or_create_by(author_name: attributes[:author_name])
    end
    def category_attributes=(attributes)
      self.category = Category.find_or_create_by(category_name: attributes[:category_name])
    end
    def publisher_attributes=(attributes)
      self.publisher = Publisher.find_or_create_by(publisher_name: attributes[:publisher_name])
    end
    def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
   joins(:category,:publisher,:author).where('category_name like ? or publisher_name like ? or author_name like ? or title like ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
  end
  def self.to_csv(a)
    CSV.generate do |csv|
    csv << column_names
      all.each do |book|
      csv << book.attributes.values_at(*column_names)
      end
  end
  end
     
end   

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
   @books = Book.paginate( page: params[:page] )
   if params[:search]
      @books = Book.search(params[:search]).page(params[:page])
   elsif params[:category_id]
			@category = Category.find params[:category_id]
      @books = @category.books.paginate( page: params[:page] )
   elsif params[:author_id]
      @author = Author.find params[:author_id]
      @books = @author.books.paginate( page: params[:page] )
   elsif params[:publisher_id]
      @publisher = Publisher.find params[:publisher_id]
      @books = @publisher.books.paginate( page: params[:page] )

	 end
   
			

   respond_to do|format|
      format.html
      format.xls{send_data @books.to_csv(col_sep: "\t") }
    end
  end

  def show
  @book = Book.find_by_id(params[:id])
  end 

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
       redirect_to books_path, notice: "Book saved"
    else
      render 'new'
    end
  end


  def edit
    @book = Book.find( params[:id] )
  end

  def update
    @book = Book.find_by_id(params[:id])
    if @book.update_attributes(book_params) # returns true only on succesful update!
      # Handle a successful update.
      flash[:success] = "Book has been successfully updated!"
      redirect_to (@book)
    else
      render 'edit'
    end
  end

  def destroy
    Book.find_by_id( params[:id] ).destroy
    flash[:success] = 'book successfully deleted!'
    redirect_to (books_url)
  end

  	def show
		@book = Book.find( params[:id] )
		if @book.reviews.blank?
			@average_review = 0
		else
			@average_review = @book.reviews.average(:rating).round(2)
		end
	end

  private

  def book_params
    params.require(:book).permit(:title,:description,:book_img, :author_attributes=> [:id,:author_name], :category_attributes=>[:id,:category_name], :publisher_attributes=>[:id, :publisher_name])
  end
  def find_book
			@book = Book.find(params[:id])
  end
  

  # Before filters

  # Confirms the correct user.
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>    
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :description %>
       <%= f.text_area(:description, :size => "50x10")%>
    <%= f.label :author %>
    <%=	f.fields_for :author_attributes do |author| %>
    <%= author.text_field :author_name, class: 'form-control' %>
    <% end %>
    <%= f.label :category %>
    <%=	f.fields_for :category_attributes do |category| %>
    <%= category.collection_select :category_name, Category.all, :category_name, :category_name %>
    <% end %>
    <%= f.label :publisher %>
    <%=	f.fields_for :publisher_attributes do |publisher| %>
    <%= publisher.text_field :publisher_name,class: 'form-control' %>
    <% end %>

    <%= f.file_field :book_img,class: 'form-control' %>
    <%= f.submit "submit", class: "btn btn-primary" %>

<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-book-form">

		<h1>Edit Book</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/books/index.html.erb
<% provide(:title, 'All Book') %>

<div class="banner-title text-center">
		     <h2><span>ALL BOOKS</span></h2>
</div>

<% if @books.count == 0 %>

	<h1>There are no books</h1>

<% else %>	
<div class="container">
	<div class="row">

		<% @books.each do |book| %>

			<div class="col-md-3">
				<a href="/books/<%= book.id %>">
					<%= image_tag book.book_img.url(:medium), class: "book" %>
					<p><%= book.title %></p>
				</a>
				
			</div>	

		<% end %>

	</div>

<% end %>	
<% if logged_in? %>
	<% if current_user.admin? %>	
		<br><%= link_to "Add Book", new_book_path %></br>
		<br><%= link_to "Export to XLS", books_path(format: "xls") %></br>
<% end %>
<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

		<h1>New Book</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/books/show.html.erb
<div class="row">

	
	<div class="col-md-4">

		<%= image_tag @book.book_img.url(:medium), class: "book-show" %>

	</div>
	

	<div class="col-md-8">

		<div class="book-info">

			<h2 class="book-title"><%= @book.title %></h2>
			<h3 class="book-author"><span>From:</span> <%= link_to @book.author.author_name, author_books_path(author_id: @book.author.id) %></h3>
			<h3 class="book-author"><span>Category:</span> <%= link_to @book.category.category_name, category_books_path(@book.category.id) %></h3>
			<h3 class="book-author"><span>Publisher:</span> <%= link_to @book.publisher.publisher_name, publisher_books_path(publisher_id: @book.publisher.id) %></h3>
			<h2 class="avg-rating">Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>
			<p class="book-desc"><%= @book.description %></p>
			

		</div>
	</div>


<div class="row">

	<div class="col-md-4">

		<div class="reviews">

			<!-- Where the reviews/ratings will go -->
			<h1>Reviews</h1>
			<%= render @book.reviews %>

			<div>
				<%if logged_in? %>
					<%= link_to "Add Review", new_book_review_path(@book), class: "btn-custom" %>
					<% end %>	
			</div>

		</div>	

	</div>

</div>

<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>

	<%if logged_in? %>
		<% if current_user.admin  %>

			<%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
			<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

		<% end %>
	<% end %>	
	

</div>	


<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>