config/routes.rb
Rails.application.routes.draw do


  get 'book/index'

  get 'book/new'

  get 'book/edit'

  get 'book/show'

  get 'publishers/index'

  get 'publishers/show'

  get 'publishers/new'

  get 'publishers/edit'

  get 'categories/new'

  get 'authors/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'books#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  # Add new routes for logging in/out
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :categories do
    resources :books
  end 
  resources :authors do
    resources :books
  end 
   resources :publishers do
    resources :books
  end 
  
  resources :users
  resources :books do
  resources :reviews
  end
  resources :publishers
  resources :authors
  resources :categories
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :relationships,       only: [:create, :destroy]
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :books, dependent:   :destroy
	validates :category_name, presence: true, length: {maximum: 50 }
	self.per_page = 10
	def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
 	 where("category_name LIKE ?", "%#{search}%")
	end
	def self.to_csv(a)
		CSV.generate do |csv|
		csv << column_names
    	all.each do |category|
     	csv << category.attributes.values_at(*column_names)
    	end
	end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   def index
 # @authors = Author.paginate( page: params[:page] )
  if params[:search]
      @categories = Category.search(params[:search]).page(params[:page])
    else
      @categories = Category.all.page(params[:page])
    end
    respond_to do|format|
      format.html
      format.xls{send_data @categories.to_csv(col_sep: "\t") }
    end
  end

  def show
  @category = Category.find_by_id(params[:id])
  end 

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
      if @category.save
      flash[:info] = 'OK'
      redirect_to(categories_url)
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by_id( params[:id] )
  end

  def update
    @category = Category.find_by_id(params[:id])
    if @category.update_attributes(category_params) # returns true only on succesful update!
      # Handle a successful update.
      flash[:success] = "Category has been successfully updated!"
      redirect_to (@category)
    else
      render 'edit'
    end
  end

  def destroy
    Category.find_by_id( params[:id] ).destroy
    flash[:success] = 'category successfully deleted!'
    redirect_to (categories_url)
  end


  private

  def category_params
    params.require(:category).permit(:category_name)
  end

  # Before filters

  # Confirms the correct user.

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_category.html.erb
<li>
  <%if logged_in?%>
  <%= link_to category.category_name, category %>
  <% if current_user.admin? %>
      | <%= link_to "delete", category, method: :delete,
                    data: { confirm: "You sure?" } %>
        |<%= link_to "edit", edit_category_path(category)%>

  <% end %>
  <% end %>

</li>

app/views/categories/edit.html.erb
<% provide(:title, "Edit Author") %>
<div class="banner-title text-center">
         <h2><span>UPDATE CATEGORY</span></h2>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :category_name, class: 'form-control' %>  
        <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, 'All Category') %>
<div class="banner-title text-center">
         <h2><span>ALL CATEGORIES</span></h2>
</div>
<% if logged_in? %>
  <% if current_user.admin? %>  
<%= link_to 'Add New Category', new_category_path, class: "btn btn-primary", style: "color: #ffffff" %>
    
  <% end %>
  <table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>ID</th>
      <th>Category Name</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |a| %>
      <tr>
      	  <td><%= a.id %></td>
        <td><%= link_to a.category_name, a %></td>
       
              
        <td><%= link_to 'Edit', edit_category_path(a), class: "btn btn-warning" , :style => "color: #ffffff"%></td>
        <td><%= link_to 'Delete', a, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" , :style => "color: #ffffff"%></td>
        <% end %>
      </table>
      <% if logged_in? %>
	<% if current_user.admin? %>	
		<br><%= link_to "Export to XLS", authors_path(format: "xls") %></br>
<% end %>
<% end %>
<%= will_paginate %>

<% end %>

app/views/categories/new.html.erb
<% provide(:title, 'Create Category') %>
<div class="banner-title text-center">
         <h2><span>CREATE CATEGORY</span></h2>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :Name %>
        <%= f.text_field :category_name, class: 'form-control' %>
        <%= f.submit "Create Category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<% provide(:title, @category.category_name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= @category.category_name %>
      </h1>
    </section>
</div>