config/routes.rb
Rails.application.routes.draw do


  get 'book/index'

  get 'book/new'

  get 'book/edit'

  get 'book/show'

  get 'publishers/index'

  get 'publishers/show'

  get 'publishers/new'

  get 'publishers/edit'

  get 'categories/new'

  get 'authors/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'books#index'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  # Add new routes for logging in/out
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :categories do
    resources :books
  end 
  resources :authors do
    resources :books
  end 
   resources :publishers do
    resources :books
  end 
  
  resources :users
  resources :books do
  resources :reviews
  end
  resources :publishers
  resources :authors
  resources :categories
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<div class="header-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-2 col-sm-6 col-xs-6">
                        <div class="header-logo">
                            <%=  link_to image_tag("logo.png"), root_path %>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="layer-4">
                            <form class="title-4">
                                <%= form_tag(books_path, :method => "get", id: "search-form") do %>
                                    <ul>
                                        <li >
                                            <%= text_field_tag :search, params[:search], placeholder: "Search" , class: 'form-control'%>
                                        </li>
                                       
                                    </ul>
                                <% end %>
                            </form>
                        </div>
                        <!--     <div class="layer-4">
                        <form action="#" class="title-4">
                            <input type="text" placeholder="Enter your book title here">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div> -->
                        
                    </div>   
                               
                    <div class="col-md-6 col-sm-12 hidden-xs">
                        <div class="mainmenu text-center">
                            <nav>
                                <ul id="nav">

                                    <li><%= link_to "HOME", root_path %></li>
                                    <li><%= link_to "CATEGORY", root_path %></a>
                                    <ul class="sub-menu">
                                            <% Category.all.each do |category| %>
                                            <li >
                                            <%= link_to category.category_name, category_books_path(category_id: category.id), class: "link" %>
                                            </li>
                                            <% end %>
                                    </ul>
                                    </li>    
                                    
                                  
                                    <li><%= link_to "ACCOUNT", root_path %></a>
                                    <ul class="sub-menu">
                                        <% if logged_in? %>
                                         <% if current_user.admin  %>
                                            <li><%= link_to "MANAGE CATEGORY", categories_path%></li>
                                            <li><%= link_to "MANAGE AUTHOR", authors_path %></li>
                                    <li><%= link_to "MANAGE PUBLISHER", publishers_path %></li>
                                        <li><%= link_to "MANAGE USER", users_path %></li>
                                        <% end %>
                                            <li><%= link_to "Profile", current_user %></li>
                                             <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                        <li class="divider"></li>
                                        <li>
                                        <%= link_to "Log out", logout_path, method: :delete %>
                                        </li>
                                            <%else%>
                                              <li><%= link_to "Log in", login_path %></li>
                                              <li><%= link_to "Sign up", signup_path %></li>
                                        <% end %>    
                                        </ul>
                                    </li>    
                                </ul>
                            </nav>
                        </div>                        
                    </div>
                    
                </div>
            </div>
        </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
   
  </div>

      <%= render 'layouts/footer' %>


    
  </body>
</html>